# Generated by Django 3.0.6 on 2020-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('New', 'New'), ('Existing', 'Existing'), ('SALE', 'SALE')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(null=True, to='h2.Tag'),
        ),
    ]
