# Generated by Django 3.0.6 on 2020-05-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2', '0003_auto_20200513_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
